# Generated by Django 3.1 on 2020-10-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_auto_20201013_1250'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dotacion',
                'verbose_name_plural': 'Dotaciones',
            },
        ),
        migrations.RemoveField(
            model_name='businessmanager',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='email_manager',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_cont_emp',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_emp_hired',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_mach_heavy',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_mach_heavy_cont',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_veh_com_cont',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_veh_com_heavy',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_veh_com_heavy_cont',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='n_veh_com_light',
        ),
        migrations.CreateModel(
            name='RangosDotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.PositiveIntegerField()),
                ('max_value', models.PositiveIntegerField()),
                ('ri_value', models.PositiveIntegerField(default=1)),
                ('dotacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.dotacion')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza')),
            ],
            options={
                'verbose_name': 'Rango Dotacion',
                'verbose_name_plural': 'Rangos Dotaciones',
            },
        ),
        migrations.CreateModel(
            name='DotacionEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('dotacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.dotacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dotacion Empresa',
                'verbose_name_plural': 'Dotaciones Empresariales',
            },
        ),
    ]
