# Generated by Django 3.1 on 2020-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguiar',
            name='building',
            field=models.ManyToManyField(blank=True, to='Poll.BuildingProcess'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='general_services',
            field=models.ManyToManyField(blank=True, to='Poll.GeneralServicesProcess'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='manufacture',
            field=models.ManyToManyField(blank=True, to='Poll.ManufactureProcess'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='process',
            field=models.ManyToManyField(to='Poll.ProcessBusiness'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='transport',
            field=models.ManyToManyField(blank=True, to='Poll.TransportProcess'),
        ),
    ]
