# Generated by Django 3.1 on 2020-08-30 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_auto_20200829_1914'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguiar',
            name='risk_management',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.riskmanagement'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='risk_prevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.riskpreventionpersonal'),
        ),
    ]
