# Generated by Django 3.1 on 2020-10-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmanager',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='email_manager',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='is_active',
        ),
    ]
