# Generated by Django 3.1 on 2020-08-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_electricityconfirmed_explosiveconfirmed_heightconfirmed_substanceconfirmed'),
        ('Home', '0002_auto_20200829_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguiar',
            name='electricity_confirmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.electricityconfirmed'),
        ),
        migrations.AddField(
            model_name='userguiar',
            name='explosive_confirmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.explosiveconfirmed'),
        ),
        migrations.AddField(
            model_name='userguiar',
            name='height_confirmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.heightconfirmed'),
        ),
        migrations.AddField(
            model_name='userguiar',
            name='substance_confirmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.substanceconfirmed'),
        ),
    ]
