# Generated by Django 3.1.1 on 2020-09-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_city_name_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguiar',
            name='enable_poll',
            field=models.BooleanField(default=True),
        ),
    ]
