# Generated by Django 3.1 on 2020-11-13 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_auto_20201108_1858'),
        ('Home', '0003_userguiar_opciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediaUserOpcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.opcion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intermedia User Opcion',
                'verbose_name_plural': 'Intermedia Users Opciones',
            },
        ),
    ]
