# Generated by Django 3.1 on 2020-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_intermediauseropcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediauseropcion',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
