# Generated by Django 3.1 on 2020-12-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_intermediauseropcion_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguiar',
            name='building',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='electricity_confirmed',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='electricity_control',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='explosive_confirmed',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='explosive_control',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='general_services',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='height_confirmed',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='height_control',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='manufacture',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='process',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='risk_management',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='risk_prevent',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='substance_confirmed',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='substance_control',
        ),
        migrations.RemoveField(
            model_name='userguiar',
            name='transport',
        ),
    ]
