# Generated by Django 3.1 on 2020-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_intermediauseropcion_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguiar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
