# Generated by Django 3.1 on 2020-12-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20201212_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguiar',
            name='opciones',
        ),
    ]
