# Generated by Django 3.1 on 2020-12-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_userguiar_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguiar',
            name='is_active',
        ),
    ]
