# Generated by Django 3.1 on 2020-12-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_userguiar_opciones'),
        ('Home', '0007_remove_userguiar_is_active'),
    ]

    operations = [
    ]
