# Generated by Django 3.1 on 2021-01-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_merge_20201216_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Token Generado',
                'verbose_name_plural': 'Tokens Generados',
            },
        ),
    ]
