# Generated by Django 3.1 on 2021-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_recoverytokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverytokens',
            name='token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
