# Generated by Django 3.1 on 2021-04-03 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0015_sales_amortiguador'),
        ('Home', '0010_auto_20210116_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediaUserVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.sales')),
            ],
            options={
                'verbose_name': 'Intermedia User Venta',
                'verbose_name_plural': 'Intermedia Users Ventas',
            },
        ),
    ]
