# Generated by Django 3.1 on 2021-04-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_intermediauserventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntermediaUserVenta',
        ),
    ]
