# Generated by Django 3.1 on 2021-05-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_delete_intermediauserventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userguiar',
            options={'verbose_name': 'Usuario Registrado', 'verbose_name_plural': 'Usuarios Registrados'},
        ),
    ]
