# Generated by Django 3.1 on 2021-05-06 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0018_auto_20210505_2014'),
        ('Home', '0013_auto_20210505_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmanager',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='nombre completo'),
        ),
        migrations.AlterField(
            model_name='businessmanager',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='businessmanager',
            name='rut_bm',
            field=models.CharField(max_length=12, unique=True, verbose_name='rut del representante'),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='dotacionempresarial',
            name='dotacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.dotacion', verbose_name='campo de dotación'),
        ),
        migrations.AlterField(
            model_name='dotacionempresarial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='rangosdotacion',
            name='dotacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.dotacion', verbose_name='campo de dotación'),
        ),
        migrations.AlterField(
            model_name='rangosdotacion',
            name='max_value',
            field=models.PositiveIntegerField(verbose_name='límite superior'),
        ),
        migrations.AlterField(
            model_name='rangosdotacion',
            name='min_value',
            field=models.PositiveIntegerField(verbose_name='límite inferior'),
        ),
        migrations.AlterField(
            model_name='rangosdotacion',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza', verbose_name='póliza asociada'),
        ),
        migrations.AlterField(
            model_name='rangosdotacion',
            name='ri_value',
            field=models.PositiveIntegerField(default=1, verbose_name='riesgo del rango'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.city', verbose_name='región'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='administrador de guiar consultores'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.businessmanager', verbose_name='representante'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Poll.sales', verbose_name='ventas anuales'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='seniority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='años de experiencia'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.town', verbose_name='ciudad'),
        ),
    ]
