# Generated by Django 3.1 on 2021-05-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20210505_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguiar',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.city', verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='userguiar',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.town', verbose_name='comuna'),
        ),
    ]
