# Generated by Django 3.1 on 2020-10-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPoliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza')),
            ],
            options={
                'verbose_name': 'Sub-Poliza',
                'verbose_name_plural': 'Sub-Polizas',
            },
        ),
        migrations.DeleteModel(
            name='DotacionInfo',
        ),
        migrations.AlterField(
            model_name='buildingprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='electricitycontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='explosivecontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='generalservicesprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='heightcontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='manufactureprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='substancecontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
        migrations.AlterField(
            model_name='transportprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza'),
        ),
    ]
