# Generated by Django 3.1 on 2020-08-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='electricitycontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='explosivecontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='generalservicesprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='heightcontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='manufactureprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='substancecontrol',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
        migrations.AddField(
            model_name='transportprocess',
            name='poliza',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza'),
        ),
    ]
