# Generated by Django 3.1 on 2020-08-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_auto_20200829_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_electricity', models.CharField(max_length=10)),
                ('value_ri_electricity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExplosiveConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_explosive', models.CharField(max_length=10)),
                ('value_ri_explosive', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HeightConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_height', models.CharField(max_length=10)),
                ('value_ri_height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_substance', models.CharField(max_length=10)),
                ('value_ri_substance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
