# Generated by Django 3.1 on 2020-09-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_electricityconfirmed_explosiveconfirmed_heightconfirmed_substanceconfirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotacionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('min_value', models.PositiveIntegerField()),
                ('max_value', models.PositiveIntegerField()),
                ('poliza', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza')),
            ],
        ),
    ]
