# Generated by Django 3.1 on 2020-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_opcion_polizadotacion_polizapregunta_pregunta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
