# Generated by Django 3.1 on 2020-09-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_dotacioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacioninfo',
            name='ri_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
