# Generated by Django 3.1 on 2020-11-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_auto_20201107_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polizadotacion',
            options={'verbose_name': 'Intermedia Poliza-Dotacion', 'verbose_name_plural': 'Intermedia Polizas-Dotaciones'},
        ),
    ]
