# Generated by Django 3.1 on 2020-09-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_dotacioninfo_ri_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacioninfo',
            name='cod',
            field=models.CharField(max_length=100),
        ),
    ]
