# Generated by Django 3.1 on 2020-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0007_auto_20201121_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='tipo',
            field=models.CharField(choices=[('1', 'Procesos'), ('2', 'Actividades')], max_length=20),
        ),
    ]
