# Generated by Django 3.1 on 2020-11-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0008_auto_20201121_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.dependencia'),
        ),
    ]
