# Generated by Django 3.1 on 2020-11-22 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Poll', '0009_auto_20201122_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediaDependenciaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.dependencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intermedia User Dependencia',
                'verbose_name_plural': 'Intermedia Users Dependencias',
            },
        ),
    ]
