# Generated by Django 3.1 on 2020-12-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20201212_2109'),
        ('Poll', '0010_intermediadependenciauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingprocess',
            name='poliza',
        ),
        migrations.DeleteModel(
            name='ElectricityConfirmed',
        ),
        migrations.RemoveField(
            model_name='electricitycontrol',
            name='poliza',
        ),
        migrations.DeleteModel(
            name='ExplosiveConfirmed',
        ),
        migrations.RemoveField(
            model_name='explosivecontrol',
            name='poliza',
        ),
        migrations.RemoveField(
            model_name='generalservicesprocess',
            name='poliza',
        ),
        migrations.DeleteModel(
            name='HeightConfirmed',
        ),
        migrations.RemoveField(
            model_name='heightcontrol',
            name='poliza',
        ),
        migrations.RemoveField(
            model_name='manufactureprocess',
            name='poliza',
        ),
        migrations.RemoveField(
            model_name='polizadotacion',
            name='dotacion',
        ),
        migrations.RemoveField(
            model_name='polizadotacion',
            name='poliza',
        ),
        migrations.DeleteModel(
            name='ProcessBusiness',
        ),
        migrations.DeleteModel(
            name='RiskManagement',
        ),
        migrations.DeleteModel(
            name='RiskPreventionPersonal',
        ),
        migrations.DeleteModel(
            name='SubstanceConfirmed',
        ),
        migrations.RemoveField(
            model_name='substancecontrol',
            name='poliza',
        ),
        migrations.RemoveField(
            model_name='transportprocess',
            name='poliza',
        ),
        migrations.DeleteModel(
            name='BuildingProcess',
        ),
        migrations.DeleteModel(
            name='ElectricityControl',
        ),
        migrations.DeleteModel(
            name='ExplosiveControl',
        ),
        migrations.DeleteModel(
            name='GeneralServicesProcess',
        ),
        migrations.DeleteModel(
            name='HeightControl',
        ),
        migrations.DeleteModel(
            name='ManufactureProcess',
        ),
        migrations.DeleteModel(
            name='PolizaDotacion',
        ),
        migrations.DeleteModel(
            name='SubstanceControl',
        ),
        migrations.DeleteModel(
            name='TransportProcess',
        ),
    ]
