# Generated by Django 3.1 on 2021-01-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0012_auto_20210103_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaDependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.dependencia')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.subpoliza')),
            ],
            options={
                'verbose_name': 'Intermedia Poliza-Dependencia',
                'verbose_name_plural': 'Intermedia Polizas-Dependencias',
            },
        ),
    ]
