# Generated by Django 3.1 on 2021-04-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0015_sales_amortiguador'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='cobertura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
