# Generated by Django 3.1 on 2021-05-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0017_auto_20210505_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amortiguador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='modificador'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='title',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='subpoliza',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Poll.poliza', verbose_name='ramo'),
        ),
        migrations.AlterField(
            model_name='subpoliza',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
    ]
